// These are from C:\Program Files (x86)\IAR Systems\Embedded Workbench 8.0\arm\config\syntax_icc.cfg
#define __arm
#define __thumb
#define __interwork
#define __swi
#define __irq
#define __fiq
#define  __ramfunc
#define __no_init
#define __root
#define __nested
#define __task
#define __noreturn
#define __absolute
#define __big_endian
#define __little_endian
#define __packed
#define __stackless
#define __weak
#define __WEAK
#define __nounwind
#define __intrinsic
